//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namiokai {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Namiokai.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string AddPage_Title {
            get {
                return ResourceManager.GetString("AddPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        public static string Admin_panel {
            get {
                return ResourceManager.GetString("Admin_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All properties are required!.
        /// </summary>
        public static string All_properties_are_required {
            get {
                return ResourceManager.GetString("All_properties_are_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namiokai.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string AppShell_tabbar_bill {
            get {
                return ResourceManager.GetString("AppShell_tabbar_bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string AppShell_tabbar_fuel {
            get {
                return ResourceManager.GetString("AppShell_tabbar_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AppShell_tabbar_home {
            get {
                return ResourceManager.GetString("AppShell_tabbar_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear database.
        /// </summary>
        public static string Clear_database {
            get {
                return ResourceManager.GetString("Clear_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear preferences.
        /// </summary>
        public static string Clear_preferences {
            get {
                return ResourceManager.GetString("Clear_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear specified sheets!.
        /// </summary>
        public static string ClearSheets_Error {
            get {
                return ResourceManager.GetString("ClearSheets_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets cleared successfully..
        /// </summary>
        public static string ClearSheets_success {
            get {
                return ResourceManager.GetString("ClearSheets_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to log in.
        /// </summary>
        public static string Click_log_in {
            get {
                return ResourceManager.GetString("Click_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to log out.
        /// </summary>
        public static string Click_log_out {
            get {
                return ResourceManager.GetString("Click_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user.
        /// </summary>
        public static string Current_user {
            get {
                return ResourceManager.GetString("Current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string Dark_mode {
            get {
                return ResourceManager.GetString("Dark_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev menu toggled.
        /// </summary>
        public static string Dev_menu_toggled {
            get {
                return ResourceManager.GetString("Dev_menu_toggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer menu.
        /// </summary>
        public static string Developer_mode {
            get {
                return ResourceManager.GetString("Developer_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string FuelPage_Title {
            get {
                return ResourceManager.GetString("FuelPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had happened?.
        /// </summary>
        public static string Had_happened {
            get {
                return ResourceManager.GetString("Had_happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/avatars/206019336970829824/430fc165141236a89c4da169b054795f.webp?size=160.
        /// </summary>
        public static string Klaidas_avatar {
            get {
                return ResourceManager.GetString("Klaidas_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaidas.
        /// </summary>
        public static string Klaidas_username {
            get {
                return ResourceManager.GetString("Klaidas_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/avatars/397387147960909824/b0930f556fa982b3118c54983f04e9c0.webp?size=160.
        /// </summary>
        public static string Klaidelis_avatar {
            get {
                return ResourceManager.GetString("Klaidelis_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaidelis.
        /// </summary>
        public static string Klaidelis_username {
            get {
                return ResourceManager.GetString("Klaidelis_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login canceled by the user..
        /// </summary>
        public static string Login_canceled_by_the_user {
            get {
                return ResourceManager.GetString("Login_canceled_by_the_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login page.
        /// </summary>
        public static string LoginPage_title {
            get {
                return ResourceManager.GetString("LoginPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namiokai.
        /// </summary>
        public static string MainPage_title {
            get {
                return ResourceManager.GetString("MainPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/avatars/332195188011433984/69aa1d5c29fb664da883418bb5437e18.webp?size=160.
        /// </summary>
        public static string Mantelis_avatar {
            get {
                return ResourceManager.GetString("Mantelis_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantelis.
        /// </summary>
        public static string Mantelis_username {
            get {
                return ResourceManager.GetString("Mantelis_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Internet connection..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoInternet page.
        /// </summary>
        public static string NoInternet_page {
            get {
                return ResourceManager.GetString("NoInternet_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers.
        /// </summary>
        public static string Passengers {
            get {
                return ResourceManager.GetString("Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymaster.
        /// </summary>
        public static string Paymaster_label {
            get {
                return ResourceManager.GetString("Paymaster_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bill.
        /// </summary>
        public static string Save_bill_label {
            get {
                return ResourceManager.GetString("Save_bill_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select passengers.
        /// </summary>
        public static string Select_passengers {
            get {
                return ResourceManager.GetString("Select_passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_title {
            get {
                return ResourceManager.GetString("SettingsPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/spreadsheets/d/10rRpIasdAhIUE8w8WJwC6K8AQhY1RQiNygE2iz3UH-8/edit?usp=sharing.
        /// </summary>
        public static string Sheets_URL {
            get {
                return ResourceManager.GetString("Sheets_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list.
        /// </summary>
        public static string Shopping_list_label {
            get {
                return ResourceManager.GetString("Shopping_list_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split bill.
        /// </summary>
        public static string Split_bill_label {
            get {
                return ResourceManager.GetString("Split_bill_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip date.
        /// </summary>
        public static string Trip_date {
            get {
                return ResourceManager.GetString("Trip_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip to home.
        /// </summary>
        public static string Trip_home {
            get {
                return ResourceManager.GetString("Trip_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip to Kaunas.
        /// </summary>
        public static string Trip_Kaunas {
            get {
                return ResourceManager.GetString("Trip_Kaunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create copy of {0}.
        /// </summary>
        public static string Unable_to_create_copy_of {
            get {
                return ResourceManager.GetString("Unable_to_create_copy_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s name.
        /// </summary>
        public static string Users_name {
            get {
                return ResourceManager.GetString("Users_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s picture.
        /// </summary>
        public static string Users_picture {
            get {
                return ResourceManager.GetString("Users_picture", resourceCulture);
            }
        }
    }
}
